myEbayApp/config/routes.rb
Rails.application.routes.draw do

 
  get 'webmaster/webmaster', to: 'webmaster#webmaster', as: :webmaster

  get 'messages', to: 'messages#index', as: :messages
  get 'messages/:id/new' , to: 'messages#new', as: :message_new
  get 'messages/:id/respond' , to: 'messages#respond', as: :message_respond
  post 'messages/:id/create', to: 'messages#create', as: :message_create
  get 'messages/:id', to: 'messages#show', as: :message
  delete 'messages/:id/', to: 'messages#destroy', as: :message_destroy
  get 'messages/:id/report', to: 'messages#report', as: :message_report

  resources :profiles, only: [:edit, :update]

  post 'search/common_search', to: 'search#common_search', as: :common_search
  get 'search', to: 'search#search', as: :search
  get 'search/google', to: 'search#google', as: :google

  post 'bid/:product_id/mini_bid', to: 'bid#create_minimum_bid', as: :new_minimum_bid
  post 'bid/:product_id/custom_bid', to: 'bid#create_custom_bid', as: :new_custom_bid
  post 'bid/:product_id/max_automatic_bid', to: 'bid#create_max_automatic_bid', as: :new_max_automatic_bid
  post 'bid/:product_id/direct_purchase', to: 'bid#direct_purchase', as: :purchase

  resources :categories
  post 'categories/:category_id/new', to: 'categories#new_child', as: :new_child_category
  post 'categories/:category_id/create', to: 'categories#create_child', as: :create_child_category

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get '' => 'products#index', as: :root

  get 'evaluations', to: 'evaluations#index'
  post 'evaluations/:evaluationable_type/:evaluationable_id/create', to: 'evaluations#create', as: :create_eval
  get 'evaluations/:evaluationable_type/:evaluationable_id/new', to: 'evaluations#new', as: :new_eval
  get 'evaluations/:id/edit', to: 'evaluations#edit', as: :edit_evaluation
  get 'evaluations/:id', to: 'evaluations#show', as: :evaluation
  patch 'evaluations/:id', to: 'evaluations#update'
  put 'evaluations/:id', to: 'evaluations#update'
  delete 'evaluations/:id', to: 'evaluations#destroy'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :products
  post 'products/:id/confirm', to: 'products#confirm', as: :confirm
  post 'products/:id/not_confirm', to: 'products#not_confirm', as: :not_confirm
  post 'products/:id/:bid_id/pay', to: 'products#pay', as: :pay
  get 'products/:id/more_days', to: 'products#seven_more_days', as: :more_days
  get 'archive', to: 'products#archive', as: :archive
  get 'recommend', to: 'products#recommend', as: :recommend

  resources :users, only: [:index, :new, :create, :show, :destroy]
  post 'users/:id/ban', to: 'users#ban', as: :user_ban
  post 'users/:id/deban', to: 'users#deban', as: :user_deban

  match 'auth/:provider/callback', to: 'sessions_fb#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions_fb#destroy', as: 'signout', via: [:get, :post]

end

myEbayApp/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :subcategories, :class_name => 'Category', :dependent => :destroy

  belongs_to :parent_category, :class_name => 'Category', :foreign_key => 'category_id', :dependent => :destroy

  has_many :products, :dependent => :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # give all products in a category and all subcategories
  def get_products(category)
    products = category.products.to_a
    category.subcategories.each do |sub|
      products += get_products(sub)
    end
    products
  end

end

myEbayApp/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: :create
  before_action :logged_in_user, :admin_user, only: [:edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name).where("name like ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @categories.map{ |tag| {:label => tag.name} }}
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.get_products(@category)
    views = @category.views+1
    @category.update_attributes(:views => views)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/new
  def new_child
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /categories/child
  # POST /categories/child.json
  def create_child
    @category = Category.new(category_params)
    @category.category_id = params[:category_id]
    parent_category = Category.find(params[:category_id])
    @category.name = parent_category.name + '_' + params[:category][:name]
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new_child }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        flash[:notice] = 'Please log in.'
        redirect_to login_path
      end
    end

    def admin_user
      redirect_to(categories_path) && flash[:notice] = 'You are not an admin.' unless current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

myEbayApp/app/helpers/categories_helper.rb
module CategoriesHelper
end

myEbayApp/app/views/categories/_form.html.erb
<%= form_for @category, :html => { :multipart => true } do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.autocomplete_field :name, categories_path %>
  </div>
  <div class="field">
    <% if logged_in? && current_user.admin? %>
    <%= f.label :Parent_category %><br>
    <%= f.number_field :category_id %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myEbayApp/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= button_to 'Show', @category, method: :get, class: "btn btn-large btn-primary" %>
<%= button_to 'Back to categories list', categories_path, method: :get, class: "btn btn-large btn-primary" %>

myEbayApp/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table id="categories">
  <thead>
    <tr>
      <th>Name</th>
      <th>Product quantity</th>
      <th>Views</th>
      <th>Direct parent category</th>
      <th>Direct subcategory</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.get_products(category).length %></td>
        <td><%= category.views %></td>
        <td><% if category.category_id != nil %><%= link_to category.parent_category.name,
                                                            category_path(category.parent_category.id) %>
            <% else %>No parent category
            <% end %></td>
        <td><% if category.subcategories.length != 0 %>
            <%= raw(category.subcategories.map{|sub| link_to sub.name,category_path(sub.id)}.join(' | ')) %>
            <% else %>No subcategory
            <% end %></td>
        <td><%= button_to 'Show category', category, method: :get, class: "btn btn-large btn-primary" %>
            <% if logged_in? %>
            <%= button_to 'Add subcategory', new_child_category_path(category.id), class: "btn btn-large btn-primary" %><% end %>
            <% if logged_in? && current_user.admin? %>
            <%= button_to 'Edit category', edit_category_path(category), method: :get, class: "btn btn-large btn-primary" %>
            <%= button_to 'Remove category', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? %>
<%= button_to 'New Parent category', new_category_path, method: :get, class: "btn btn-large btn-primary" %>
<% end %>

myEbayApp/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= button_to 'Back to categories list', categories_path, method: :get, class: "btn btn-large btn-primary" %>

myEbayApp/app/views/categories/new_child.html.erb
<h1>New Subcategory</h1>

<%= form_for @category,:url => create_child_category_path(params[:category_id]), :html => { :multipart => true } do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.autocomplete_field :name, categories_path %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= button_to 'Back to category', category_path(params[:category_id]), method: :get, class: "btn btn-large btn-primary" %>

myEbayApp/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Views:</strong>
  <%= @category.views %>
</p>

<p>
  <strong>Parent category:</strong>
  <% if @category.category_id != nil %>
  <%= link_to @category.parent_category.name, category_path(@category.category_id) %>
  <% else %>No parent category
  <% end %>
</p>

<p>
  <strong>Subcategories:</strong>
  <% if @category.subcategories.length != 0 %>
    <ul><% subcat = Hash.new %>
      <% @products.each do |sub| %>
          <% subcat[sub.category.id] = sub.category.name %>
      <% end %>
      <% subcat.each do |subid, subname| %>
          <li><%= link_to subname, category_path(subid) %></li>
      <% end %>
    </ul>
<% else %>No subcategory
<% end %>
</p>

<p>
  <strong>Products:</strong> <%= @products.length %>
  <% if @products.length != 0 %>
  <ul>
  <% @products.each do |prod| %>
    <li><%= link_to prod.title, product_path(prod.id) %></li>
      <% end %>
  </ul>
  <% end %>
</p>

<div id="fb-root"></div>
<div class="fb-share-button" data-layout="button_count" data-mobile-iframe="true"></div>

<% if logged_in? %>
  <%= button_to 'Add subcategory', new_child_category_path(@category), class: "btn btn-large btn-primary" %>
  <%= button_to 'Edit category', edit_category_path(@category), method: :get, class: "btn btn-large btn-primary" %>
<% end %>
<%= button_to 'Back to category list', categories_path, method: :get, class: "btn btn-large btn-primary" %>