myEbayApp/config/routes.rb
Rails.application.routes.draw do

 
  get 'webmaster/webmaster', to: 'webmaster#webmaster', as: :webmaster

  get 'messages', to: 'messages#index', as: :messages
  get 'messages/:id/new' , to: 'messages#new', as: :message_new
  get 'messages/:id/respond' , to: 'messages#respond', as: :message_respond
  post 'messages/:id/create', to: 'messages#create', as: :message_create
  get 'messages/:id', to: 'messages#show', as: :message
  delete 'messages/:id/', to: 'messages#destroy', as: :message_destroy
  get 'messages/:id/report', to: 'messages#report', as: :message_report

  resources :profiles, only: [:edit, :update]

  post 'search/common_search', to: 'search#common_search', as: :common_search
  get 'search', to: 'search#search', as: :search
  get 'search/google', to: 'search#google', as: :google

  post 'bid/:product_id/mini_bid', to: 'bid#create_minimum_bid', as: :new_minimum_bid
  post 'bid/:product_id/custom_bid', to: 'bid#create_custom_bid', as: :new_custom_bid
  post 'bid/:product_id/max_automatic_bid', to: 'bid#create_max_automatic_bid', as: :new_max_automatic_bid
  post 'bid/:product_id/direct_purchase', to: 'bid#direct_purchase', as: :purchase

  resources :categories
  post 'categories/:category_id/new', to: 'categories#new_child', as: :new_child_category
  post 'categories/:category_id/create', to: 'categories#create_child', as: :create_child_category

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get '' => 'products#index', as: :root

  get 'evaluations', to: 'evaluations#index'
  post 'evaluations/:evaluationable_type/:evaluationable_id/create', to: 'evaluations#create', as: :create_eval
  get 'evaluations/:evaluationable_type/:evaluationable_id/new', to: 'evaluations#new', as: :new_eval
  get 'evaluations/:id/edit', to: 'evaluations#edit', as: :edit_evaluation
  get 'evaluations/:id', to: 'evaluations#show', as: :evaluation
  patch 'evaluations/:id', to: 'evaluations#update'
  put 'evaluations/:id', to: 'evaluations#update'
  delete 'evaluations/:id', to: 'evaluations#destroy'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :products
  post 'products/:id/confirm', to: 'products#confirm', as: :confirm
  post 'products/:id/not_confirm', to: 'products#not_confirm', as: :not_confirm
  post 'products/:id/:bid_id/pay', to: 'products#pay', as: :pay
  get 'products/:id/more_days', to: 'products#seven_more_days', as: :more_days
  get 'archive', to: 'products#archive', as: :archive
  get 'recommend', to: 'products#recommend', as: :recommend

  resources :users, only: [:index, :new, :create, :show, :destroy]
  post 'users/:id/ban', to: 'users#ban', as: :user_ban
  post 'users/:id/deban', to: 'users#deban', as: :user_deban

  match 'auth/:provider/callback', to: 'sessions_fb#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions_fb#destroy', as: 'signout', via: [:get, :post]

end

myEbayApp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token

  has_secure_password

  has_many :messages, dependent: :destroy

  has_many :products, dependent: :destroy

  has_many :evaluations, :as => :evaluationable, :dependent => :destroy

  has_many :bids, dependent: :destroy

  has_many :purchases, :class_name => 'Product', :foreign_key => 'buyer_id'

  belongs_to :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile

  before_save { self.email = email.downcase }

  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, confirmation: true
  validates :password, length: {minimum: 6}, allow_nil: true
  validates :email, uniqueness: { case_sensitive: false }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def my_bids_in_progress(user)
    my_auctions = Hash.new
    user.bids.each do |bid|
      my_auctions[bid.product_id] = bid.product.title
    end
    my_auctions
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = SecureRandom.urlsafe_base64
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      profile = Profile.where(:uid => auth.uid, :provider => auth.provider).first_or_create
      user.profile_id = profile.id 
      user.save      
    end
  end

  def winner_or_not(product_id)
    product = product.find(product_id)
    bid = product.bid_winner(product)
    bid.user.profile.nickname
  end
end

myEbayApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :ban, :deban]
  before_action :logged_in_user, only: :destroy
  before_action :correct_user, only: :destroy


  # GET /users
  # GET /users.json
  def index
    #@users = User.order(:nickname).where("nickname like ?", "%#{params[:term]}%")
    #respond_to do |format|
    #format.html
    #format.json { render json: @users.map{ |tag| {:label => tag.nickname} }}
    #end
    @users = User.all
  end

  def show
    views = @user.views+1
    @user.update_attributes(:views => views)
    @products = Product.where(:status => 'archive', :user_id => @user.id)
  end

  # GET /users/new
  def new
    if logged_in?
      flash[:notice] = 'You are already a member.'
      redirect_to users_path
    end
    @user = User.new
  end

  def ban
    @user.update(:ban => true)
    UserMailer.ban(@user).deliver_now
    flash[:notice] = 'Email was send to ' + @user.profile.first_name + ' ' + @user.profile.last_name + '.'
    redirect_to users_path
  end

  def deban
    @user.update(:ban => false)
    UserMailer.deban(@user).deliver_now
    flash[:notice] = 'Email was send to ' + @user.profile.first_name + ' ' + @user.profile.last_name + '.'
    redirect_to users_path
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @profile = Profile.new
    @profile.save
    @user.profile_id = @profile.id
    respond_to do |format|
      if @user.save
        UserMailer.register(@user).deliver_now
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def logged_in_user
    unless logged_in?
      flash[:notice] = 'Please log in.'
      redirect_to login_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(users_path) && flash[:notice] = 'It is not you.' unless current_user?(@user)
  end

  def admin_user
    redirect_to(users_path) && flash[:notice] = 'You are not an admin.' unless current_user.admin?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :ban,:password, :profile_id, :password_confirmation, :admin, :remember_token)
  end
end

myEbayApp/app/helpers/users_helper.rb
module UsersHelper

  def current_user?(user)
    user == current_user || current_user.admin?
  end

end

myEbayApp/app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if logged_in? && current_user.admin? %>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.text_field :admin %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myEbayApp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table id="users">
  <thead>
    <tr>
      <th>Picture</th>
      <% if logged_in? && current_user.admin? %>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Adress</th>
      <% end %>
      <th>Nickname</th>
      <th>Product quantity</th>
      <th>Views</th>
      <th>Rate</th>
      <th>Ban?</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><% if user.profile.image.url != nil %><div class="img"><%= image_tag user.profile.image.url %></div>
            <% else %>empty
            <% end %></td>
        <% if logged_in? && current_user.admin? %>
        <td><%= user.email %></td>
        <td><%= user.profile.first_name %></td>
        <td><%= user.profile.last_name %></td>
        <td><%= user.profile.street_number %>, <%= user.profile.street_name %>, <%= user.profile.postcode %>,
            <%= user.profile.city %>, <%= user.profile.country %></td>
        <% end %>
        <td><%= user.profile.nickname %></td>
        <td><%= user.products.length %></td>
        <td><%= user.views %></td>
        <td><% if user.evaluations.length != 0 %>
              <% note = 0 %>
              <% user.evaluations.each do |evaluation| %>
                  <% note += evaluation.rate %>
              <% end %>
              <%= note.round(2) / user.evaluations.length %> / 5
          <% else %>
              empty
          <% end %></td>
        <td><%= user.ban %>  
        <td><%= button_to 'Show user', user, method: :get, class: "btn btn-large btn-primary" %>
        <% if logged_in? %>
        <%= link_to 'Add evaluation', new_eval_path('User', user), class: "btn btn-large btn-primary" %>
        <% end %>
        <% if logged_in? && (current_user.id == user.id || current_user.admin?) %>
        <%= button_to 'Edit user', edit_profile_path(user), method: :get, class: "btn btn-large btn-primary" %>
        <%= button_to 'Remove user', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %><% end %>
        <% if logged_in? && current_user.admin? && user.ban == false %>
          <%= button_to 'Ban user', user_ban_path(user), class: "btn btn-large btn-primary" %>
        <% elsif logged_in? && current_user.admin? && user.ban == true %>
          <%= button_to 'Deban user', user_deban_path(user), class: "btn btn-large btn-primary" %>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !logged_in? %>
  <%= button_to 'New user', new_user_path, method: :get, class: "btn btn-large btn-primary" %>
<% end %>

myEbayApp/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= button_to 'Back to users list', users_path, method: :get, class: "btn btn-large btn-primary" %>

myEbayApp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <% if @user.profile.image.url != nil %>
     <div id="img"><%= image_tag @user.profile.image.url.to_s %></div>
  <% else %>empty
  <% end %>
</p>

<% if logged_in? && (current_user.admin? || current_user.id == @user.id) %>
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @user.profile.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.profile.last_name %>
    </p>

    <p>
      <strong>Adress:</strong>
      <%= @user.profile.street_number %>, <%= @user.profile.street_name %>, <%= @user.profile.postcode %>,
      <%= @user.profile.city %>, <%= @user.profile.country %>
    </p>
<% end %>

<p>
  <strong>Nickname:</strong>
  <%= @user.profile.nickname %>
</p>

<% if logged_in? && (current_user.admin? || current_user.id == @user.id) %>

    <p>
      <strong>My auctions:</strong>
      <% if @user.bids.length != 0 %>
        <button id="auction">Hide auctions</button>
        <ul id="auctions">
          <% @user.my_bids_in_progress(@user).each do |product_id, product_title| %>
              <li><%= link_to product_title, product_path(product_id) %> : winner is <%= @user.winner_or_not(product_id) %></li>
          <% end %>
        </ul>
      <% else %>No auction in progress
      <% end %>
    </p>

    <p>
      <strong>Products sold:</strong>
      <% if @products.length != 0 %>
        <button id="sell">Hide products sold</button>
        <ul id="sells">
          <% @products.each do |product| %>
              <li><%= link_to product.title, product_path(product.id)  %></li>
          <% end %>
        </ul>
    <% else %>
        empty
    <% end %>
    </p>

    <p>
      <strong>Products bought:</strong>
      <% if @user.purchases.length != 0 %>
        <button id="purchase">Hide products bought</button>
        <ul id="purchases">
          <% @user.purchases.each do |purchase| %>
              <li><%= link_to purchase.title, product_path(purchase.id) %></li>
          <% end %>
        </ul>
    <% else %>
        empty
    <% end %>
    </p>
<% end %>

<p>
  <strong>Products:</strong>
  <% if @user.products.length != 0 %>
  <button id="product">Hide products</button>
    <ul id="products">
      <% @user.products.each do |product| %>
          <li><%= link_to product.title, product_path(product.id) %><% if logged_in? && 
            (current_user.id == @user.id || current_user.admin?) %> : <%= product.status %><% end %></li>
      <% end %> 
    </ul>
<% else %>
    empty
<% end %>
</p>

<p>
  <strong>Views:</strong>
  <%= @user.views %>
</p>

<p>
  <strong>Rate:</strong>
  <% if @user.evaluations.length != 0 %>
      <% note = 0 %>
      <% @user.evaluations.each do |evaluation| %>
          <% note += evaluation.rate %>
      <% end %>
      <%= note.round(2) / @user.evaluations.length %> / 5
  <% else %>
      empty
  <% end %>
</p>

<p>
  <strong>Evaluations:</strong>
  <% if @user.evaluations.length != 0 %>
    <button id="evaluation">Hide evaluations</button>
    <ul id="evaluations">
      <% @user.evaluations.each do |evaluation| %>
          <li><strong>Author:</strong> <% if logged_in? && current_user.admin? %><%= link_to evaluation.author_name,
                                                                               user_path(evaluation.user_id) %>
                <% else %><%= link_to evaluation.author_nickname, user_path(evaluation.user_id) %>
            <% end %><strong>Note:</strong> <%= evaluation.rate %> / 5
            <strong> Comment:</strong> <%= evaluation.content %></li>
      <% end %>
    </ul>
<% else %>
    empty
<% end %>
</p>

<p>
  <strong>Ban:</strong>
  <%= @user.ban %>
</p>

<div id="fb-root"></div>
<div class="fb-share-button" data-layout="button_count" data-mobile-iframe="true"></div>

<% if logged_in? && current_user.id != @user.id %>
    <%= link_to 'Add evaluation', new_eval_path('User', @user), class: "btn btn-large btn-primary" %>
<% end %>
<% if logged_in? && (current_user.id == @user.id || current_user.admin?) %>
    <%= button_to 'Edit user', edit_profile_path(@user), method: :get, class: "btn btn-large btn-primary" %>
    <%= button_to 'Remove user', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %>
<% end %>
<%= button_to 'Back to users list', users_path, method: :get, class: "btn btn-large btn-primary" %>
<% if logged_in? && current_user.admin? && @user.ban == false %>
<%= button_to 'Ban user', user_ban_path(@user), class: "btn btn-large btn-primary" %>
<% elsif logged_in? && current_user.admin? && @user.ban == true %>
<%= button_to 'Deban user', user_deban_path(@user), class: "btn btn-large btn-primary" %>
<% end %>